baseURL = "/"
languageCode = "en-uk"
title = "Brisbane Open Research Network"
theme = "timer-hugo"

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
# We Used Ionicons Icon font for Icon, for more details check this link - https://ionicons.com/

# Site Menus
[menu]
    # Navbar Menus
    [[menu.nav]]
        name    = "About"
        url     = "/about"
        weight  = 2
    [[menu.nav]]
        name    = "Code of Conduct"
        url     = "/coc"
        weight  = 3
    #[[menu.nav]]
    #    name    = "Gallery"
    #    url     = "/gallery"
    #    weight  = 4
    [[menu.nav]]
        name    = "Blog"
        url     = "/blog"
        weight  = 4
    #[[menu.nav]]
    #    name    = "Contact"
    #    url     = "/contact"
    #    weight  = 4

# Site Params
[params]
    home = "Home"
    logo = "images/ferris-wheel-name.png"
    dateFormat = "6 January 2006"

    # Banner Section
    [params.banner]
        enable  = true
        bgImage = "images/bg.jpg"
        heading = "WELCOME TO THE BRISBANE OPEN RESEARCH NETWORK"
        description = "A hub for Open Research practitioners in Brisbane, Australia."
        #btn     = true
        #btnText = "Download More"
        #btnURL  = "https://themefisher.com/"
        [[params.banner.flipText]]
            title   = "COMMUNITY"
        [[params.banner.flipText]]
            title   = "ADVOCACY"
        [[params.banner.flipText]]
            title   = "EDUCATION"
        [[params.banner.flipText]]
            title   = "RESOURCES"

    # Homepage About Section
    [params.about]
        enable  = true
        title   = "ABOUT THE NETWORK"
        content = "Open science and open research practices are growing in Australia, but it can be difficult to know who else is engaging in these practices. The Brisbane Open Research Network (BORN) is part of a larger network throughout Australia and New Zealand (ANZORN) aimed at promoting open research and helping to connect people to share resources, practices, and a sense of community. If you're not in Brisbane but like the sound of the community, check out the other communities in our network below. </br></br>We aim to help you find like-minded folks, support efforts to reform institutional policies and practices, and educate others about open research.</br></br>Follow our <a href='https://twitter.com/BrisOpenRes' target='_blank'>Twitter account</a> for updates.</br></br>BORN is an inclusive and welcoming community by design — to preserve this, BORN activities are subject to our <a href='https://born.netlify.com/coc' target='_blank'>Code of Conduct</a>."
        image   = "images/about/ferris-wheel.png"

    # Call to Action
    [params.cta]
        enable  = true
        title   = "ANZORN Networks"
        content = "Want to connect with one of our partner networks?"
        btnMText = "Melbourne"
        btnSText = "Sydney"
        btnPText = "Perth - coming soon"
        btnAText = "Adelaide - coming soon"
        btnNZText = "New Zealand"

    # Portfolio Section On Homepage
    [params.portfolio]
        enable  = false
        title   = "ANZORN Networks"
        subtitle= "Want to connect with one of our partner networks?"

    # Feature Product Section
    [params.feature]
        enable  = false
        title   = "SOME OF OUR FEATURES WORKS"
        subtitle= "Aliquam lobortis. Maecenas vestibulum mollis diam. Pellentesque auctor neque nec urna. Nulla sit amet est. Aenean posuere <br> tortor sed cursus feugiat, nunc augue blandit nunc, eu sollicitudin urna dolor sagittis lacus."

    
