---
title: "Interim Code of Conduct"
author: "BORN steering committee"
date: "13 November 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Summary

The Brisbane Open Research Network (BORN) seeks to promote open practices, and as part of this vision is committed to the provision of a safe, inclusive, welcoming and harassment-free atmosphere to all. 
All parties to activities associated with the Network are required to be compliant with the code of conduct.
If you observe something that you do not feel is consistent with these principles, please report them to the steering committee. 

 
## Full Code and scope

All parties to BORN activities are subject to this code of conduct, this includes attendees, speakers, sponsors, and committee members and its provisions apply to both physical and non-physical spaces (e.g. on BORN associated social media platforms).

The Brisbane Open Research Network (BORN) seeks to promote open practices. We are committed to the provision of a safe, inclusive, welcoming and harassment-free atmosphere to all irrespective of race, gender, sexual orientation, ability, religious beliefs (or lack thereof), political beliefs, age, physical appearance, body size or socioeconomic status. 

It is expected that parties to BORN activities:

-	Participate authentically, it is important to the strength of the network that our diversity is represented in its members.

-	Be considerate and respectful of other persons and their personal boundaries

-	Participate in a spirit of collaboration, and avoid conflict.

-	Refrain from demeaning, discriminatory, or harassing behaviour or speech.

-	Be supportive of fellow participants, and alert committee members where you see someone in distress or witness a code of conduct violation (however minimal).


The following behaviours are considered harassment and are proscribed within the community and its activities:

- Violence, threats of violence or violent language directed against another person

- Sexist, racist, homophobic, transphobic, ableist, or otherwise discriminatory jokes and language

- Posting or displaying sexually explicit or violent material

- Posting or threatening to post other people’s personally identifying information ("doxing")

- Personal insults, particularly those related to gender, sexual orientation, race, religion, or disability

- Inappropriate photography or recording

- Inappropriate physical contact. You should have someone’s consent before touching them in any way

- Unwelcome sexual attention. This includes sexualized comments or jokes, inappropriate touching, groping, and unwelcome sexual advances

- Intimidation, stalking, or following (online or in person)

- Advocating for, or encouraging, any of the above behaviour

- Sustained disruption of community events, including talks and presentations


Unacceptable behaviour from any community member, including sponsors and those with decision-making authority, will not be tolerated.

Anyone asked to stop unacceptable behaviour is expected to comply immediately.

If a community member engages in unacceptable behaviour, the community organizers may take any action they deem appropriate, up to and including a temporary ban or permanent expulsion from the community without warning.



This Code is adapted from the Open Source and Feelings and rOpenSci Codes of Conduct.
